# Generated by Django 3.0.7 on 2021-10-23 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='contenido',
            field=models.CharField(max_length=600, verbose_name='contenido'),
        ),
    ]
