# Generated by Django 3.0.7 on 2021-10-26 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20211025_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['created'], 'verbose_name': 'blog', 'verbose_name_plural': 'blogs'},
        ),
    ]
