# Generated by Django 3.0.7 on 2021-10-26 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20211025_2343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-id'], 'verbose_name': 'blog', 'verbose_name_plural': 'blogs'},
        ),
    ]
