# Generated by Django 2.2.3 on 2021-09-01 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_auto_20210831_2342'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
