# Generated by Django 3.0.7 on 2021-11-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_servicio_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='caracteristicas',
            field=models.TextField(default=1, max_length=1000, verbose_name='caracteristicas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='materiales',
            field=models.TextField(default=1, max_length=1000, verbose_name='materiales'),
            preserve_default=False,
        ),
    ]
